---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: site/index.md
  label: Homepage
  templates:
  - settings
- type: directory
  path: site/works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: site/journal
  label: Journal
  create: all
  match: "**/[!index]*"
  templates:
  - journal
- type: heading
  label: Data
- type: document
  path: site/config.json
  label: Site Config
upload_dir: site/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: site/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
